### ISSUE TITLE
Unsure how to use the script

### ISSUE THREAD

**Issue by rcastano** [sosy-lab/tbf#1]
Hi,

I tried to use the script with the file `c/regression/drivers--block--drbd--drbd.ko_419.63a6d0b.08_1a.cil_false-unreach-call.i` from [sv-benchmarks](https://github.com/sosy-lab/sv-benchmarks) and it seems like the script fails at linking time.

I'm running `./run_iuv -64 -i random --execution test1/drivers--block--drbd--drbd.ko_419.63a6d0b.08_1a.cil_false-unreach-call.i --timelimit 10 -v --no-parallel` and getting tons of undefined references. Am I using the script as expected? Am I missing any parameters?

**Comment by lembergerth** [comment]
Hi,

you're using the the script completely right.
The undefined references are real undefined references in the program.
While TBF can handle undefined methods and create a test harness for them,
it currently does not support undefined program variables, as in the example program, e.g., `extern unsigned long volatile jiffies;` (but there are a lot more).

**Comment by rcastano** [comment]
Hi,

Thank you for your prompt answer!
I have a few follow-up questions, let me know if this is the right place or if you'd rather continue this over email.
1) do you have a list of sv-comp files that tbf supports? 
2) do you think it'd be straightforward to extend tbf to handle these undefined references?

Thank you very much!

**Comment by lembergerth** [comment]
Sorry for the delay!
I think it's fine to handle this here, since it's still about the original question.

1. I just created one, based on an example run of the random generator. You can find it [here][1]. It is based on revision [879e141f](https://github.com/sosy-lab/sv-benchmarks/commit/879e141f) of the sv-benchmarks, so it's not the newest, beware of that. 
2. If you assume that these variable values are never changed outside of your program, it should be straightforward for primitive types and structs that only consist of primitive types. You would have to create a custom `main` method in which you initialize these undefined variables. For pointers, more thought would have to go into it. You could initialize them with 0 and hope that they are not used. But it may also be possible to collect all variables of the type of the pointer, introduce a new, non-deterministic selector-function that the test-case generator also generates a value for, and create a switch statement where each case chooses one of the possible addresses. I'm not sure whether that's smart, but I don't have a better idea right now.

[1]: https://github.com/sosy-lab/tbf/files/2215535/compilable_tasks.txt

**Comment by lembergerth** [comment]
This can be closed due to inactiveness
